export { default as Landing } from "./Landing";
export { default as Home } from "./Home";
export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as Profile } from "./Profile";
export { default as Lendings } from "./Lendings";
export { default as Friends } from "./Friends";
export { default as FriendsLibrary } from "./FriendsLibrary";
export { default as BookDetails } from "./BookDetails";
